### ISSUE TITLE
Support for running without XServer

### ISSUE THREAD

**Issue by AshitakaLax** [BallAerospace/cosmos-docker#4]
Hi Ryan,
I have a use case where we are developing against Cosmos, but not using cosmos's Gui. That said, I know that it is a gui tool.
For my current uses(verify that I have streamed in telemetry and sent commands to cosmos) I'm just using the API.
Also to automate starting the CmdTlmServer I just start it directly. Using the following command
```./Cosmos/tools/CmdTlmServer &```

When I try and run with the following docker-compose settings.
```yaml
  cosmos:
    image: "ballaerospace/cosmos"
    ports:
      - 127.0.0.1:42430:42430 # File ingest telemetry port
      - 127.0.0.1:7777:7777 # Command port
      - 127.0.0.1:7779:7779 # Telemetry output port
    #volumes:
      #- /c/COSMOS/Demo:/cosmos
      #- ./Cosmos:/cosmos
```
Launcher: cannot connect to X server

Or when I run with a custom configuration
```yaml
  cosmos:
    image: "ballaerospace/cosmos"
    ports:
      - 127.0.0.1:42430:42430 # File ingest telemetry port
      - 127.0.0.1:7777:7777 # Command port
      - 127.0.0.1:7779:7779 # Telemetry output port
    volumes:
      - ./Cosmos:/cosmos
```
I get a different error.
```
sh: 1: zenity: not found
sh: 1: notify-send: not found
/var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'ruby-termios (~> 0.9)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:258:in `each'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:258:in `verify_gemfile_dependencies_are_found!'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:49:in `start'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/resolver.rb:22:in `resolve'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/definition.rb:258:in `resolve'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
from /var/lib/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
from /cosmos/tools/tool_launch.rb:14:in `tool_launch'
from Launcher:13:in `<main>'
```

I have ran Cosmos 5.0 and can see how this may not be worth the effort supporting it in 4.x.
Thanks,
(SDL)
